package utilities

object SQL {
    const val SELECT_ALL_ANIMALES = "SELECT * FROM ANIMALES"
    const val SELECT_ALL_PERROS = "SELECT * FROM ANIMALES WHERE UPPER(TIPO) LIKE 'PERRO' "
    const val SELECT_ALL_GATOS = "SELECT * FROM ANIMALES WHERE UPPER(TIPO) LIKE 'GATO'"


}